name: PR Checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Setup mise
        uses: jdx/mise-action@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Run tests
        run: mise run test
  publish:
    name: Check that the publish plugin works
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Setup mise
        uses: jdx/mise-action@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Check that the publish plugin works
        run: mise run publish-local
  compile-test-snippets:
    name: Compile test snippets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Setup mise
        uses: jdx/mise-action@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Compile the snippets in the tests
        run: mise run test-snippets
